version: "3"
services:
    db:
        image: postgres
        networks:
            - basseynet
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_DB: exodusappdb
            POSTGRES_PASSWORD: postgres
        ports: 
            - '5430:5432'
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
        volumes: 
            - ./pgdata:/var/lib/postgresql/data
    
networks: 
    basseynet: